version: 2
updates:
  # root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "🤖 dependabot 🤖"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    ignore: # ignore updates for react-native deps, think about updating, once react-native is updated
      - dependency-name: "@babel/core"
      - dependency-name: "@babel/runtime"
      - dependency-name: "@react-native-community/eslint-config"
      - dependency-name: "eslint"
      - dependency-name: "jest"
      - dependency-name: "metro-react-native-babel-preset"
      - dependency-name: "react-test-renderer"
      - dependency-name: "react"
      - dependency-name: "react-native"
      - dependency-name: "jest-cli"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-native"
      - dependency-name: "@types/jest"
  # example
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "monthly"
    labels:
      - "🤖 dependabot 🤖"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
  # gh-actions workflow files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      core:
        patterns:
          - "react"
          - "react-native"
          - "@mapbox/*"
          - "@turf/*"
          - "@expo/config-plugins"
      dev:
        patterns:
          - "jest"
          - "@testing*"
          - "@types/*"
          - "typescript"
          - "@babel/*"
          - "babel*"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "lint*"
          - "@react-native-community/*"
          - "documentation"
          - "ejs*"
          - "husky"
          - "metro-*"
          - "prettier"
      example:
        patterns:
          - "expo*"
          - "react-*"
          - "react-native*"
          - "@react-native*"
          - "@react-navigation*"
          - "fbjs"
          - "detox"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "🤖 dependabot 🤖"
